import type { NextPage } from 'next'
import Head from 'next/head'
import Phone from '../components/Phone'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Phone />
      

      {/* Simple booking

      Stay in touch with our dog walkers through the chat interface. This makes it easy to
      discuss arrangements and make bookings. Once the walk has been completed you can rate
      your walker and book again all through the chat. */}

    </div>
  )

}

export default Home
