import type { NextPage } from 'next'
import Head from 'next/head'
import Phone from '../components/Phone'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`${styles.wrapper} flex flex-jc-c flex-ai-c`}>
        <div className={`${styles.wrapper__phone}`}>
          <Phone />
        </div>


        <div className={`${styles.wrapper__text} pad pad-lr`}>
          <h2 className='m m-xl'>Simple booking</h2>

          <p>
            Stay in touch with our dog walkers through the chat interface. This makes it easy to
            discuss arrangements and make bookings. Once the walk has been completed you can rate
            your walker and book again all through the chat.
          </p>
        </div>

      </div>
    </div>
  )

}

export default Home
